- name: Load Logstash
  ansible.builtin.include_tasks: logstash.yml
    when: elk_conponent == "logstash"

- name: Load Filebeat
  ansible.builtin.include_tasks: filebeat.yml
    when: elk_conponent == "filebeat"